---
- name: install apache
  zypper: name="{{item}}" state=present
  with_items:
  - apache2
  - apache2-mod_wsgi

- name: enable apache service
  service: name=apache2 enabled=yes

- name: check if wsgi enabled
  command: a2enmod -q wsgi
  register: mod_wsgi
  ignore_errors: True
  changed_when: False

- name: enable wsgi
  command: a2enmod wsgi
  when: mod_wsgi.rc != 0  # wsgi is disabled
  notify: reload and restart apache

- name: ensure apache is running
  when: mod_wsgi.rc == 0  # wsgi is enabled
  service: name=apache2 state=started
