- name: Remove package repository
  zypper_repository: name=jenkins state=absent

- name: Add Jenkins repository
  zypper_repository:
      name=jenkins disable_gpg_check=yes
      repo='{{ jenkins_repo_server }}/{{ jenkins_repo_path }}'

- name: Install packages for jenkins-server
  zypper: name={{ item }} state=latest
  with_items:
   - jenkins
   - dejavu-fonts
# dejavu-fonts is needed because a bug in jenkins. Although we
# set property java.awt.headless=true, the font is still needed
# when jenkins server starts. It's a work around, maybe we can
# remove it in future version of jenkins.

- name: Create Jenkins config
  template: src=etc-sysconfig-jenkins.j2
    dest=/etc/sysconfig/jenkins
    mode=0644 owner=root group=root

- name: Jenkins is enabled and running
  service: name=jenkins state=running enabled=yes
