---
- name: install mysql server
  zypper: name="{{item}}" state=present
  with_items:
  - mysql-community-server

- name: enable and start mysql server
  service: name=mysql state=started enabled=yes
