- name: Create repository configuration for zypper
  zypper_repository: name=obs state=present
    repo='http://{{ obs_repo_gw }}/{{ obs_repo_path }}/OBS:/Server:/{{ obs_version }}/openSUSE_{{ ansible_distribution_version }}/'
