---
- name: install apache module {{ module_name }}
  zypper: name="{{item}}" state=present
  with_items:
  - apache2-mod_{{ module_name }}

- name: check if apache module {{ module_name }} is enabled
  command: a2enmod -q {{ module_name }}
  register: mod_enabled
  ignore_errors: True
  changed_when: False

- name: enable apache module {{ module_name }}
  command: a2enmod {{ module_name }}
  when: mod_enabled.rc != 0  # was not listed in apache modules
  notify: reload and restart apache
