- name: ntp installed
  zypper: name={{ item }} state=installed
  with_items:
    - ntp

- name: NTP server config
  lineinfile:
    state: present
    dest: /etc/ntp.conf
    line: 'server {{ ntp }} iburst'

- name: be sure ntpd is running and enabled in 13.1
  service: name=ntp state=running enabled=yes
  when: ansible_distribution_version == "13.1"

- name: be sure ntpd is running and enabled in 13.2
  service: name=ntpd state=running enabled=yes
  when: ansible_distribution_version == "13.2"

