---
- name: install socat
  sudo: yes
  zypper: name="{{item}}" state=present
  with_items:
  - socat

- name: put gitproxy to /usr/local/bin
  template: src=gitproxy  dest=/usr/local/bin/ mode=0755

- name: config git proxy
  command: git config --system core.gitproxy gitproxy
